2024-02-23 23:30:28.196 | INFO     | handlers.default_handlers.main_menu:bot_main:21 - Current state: UserInputState:main
2024-02-23 23:30:30.476 | INFO     | handlers.custom_handlers.random_handler:bot_rand_content:20 - Current state: UserInputState:rand
2024-02-23 23:30:37.938 | ERROR    | handlers.custom_handlers.random_handler:callback_rand_film:32 - An error has been caught in function 'callback_rand_film', process 'MainProcess' (71598), thread 'WorkerThread1' (6172946432):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x101187ba0>
    └ <WorkerThread(WorkerThread1, started daemon 6172946432)>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x102ad0cc0>
    └ <WorkerThread(WorkerThread1, started daemon 6172946432)>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telebot/util.py", line 90, in run
    task(*args, **kwargs)
    │     │       └ {'handlers': [{'function': <function callback_awaits at 0x102bcc720>, 'pass_bot': False, 'filters': {'func': <function <lambd...
    │     └ (<telebot.types.CallbackQuery object at 0x102bf9510>,)
    └ <bound method TeleBot._run_middlewares_and_handler of <telebot.TeleBot object at 0x102a4a250>>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telebot/__init__.py", line 6720, in _run_middlewares_and_handler
    result = handler['function'](message)
             │                   └ <telebot.types.CallbackQuery object at 0x102bf9510>
             └ {'function': <function callback_rand_film at 0x102bcd8a0>, 'pass_bot': False, 'filters': {'func': <function <lambda> at 0x102...

> File "/Users/artem/Documents/PROGRAMMING/My/telebot/telebot_movie/handlers/custom_handlers/random_handler.py", line 32, in callback_rand_film
    text1, text2, poster = random_films_api.random_films_api()
                           │                └ <function random_films_api at 0x102a54400>
                           └ <module 'api.random_films_api' from '/Users/artem/Documents/PROGRAMMING/My/telebot/telebot_movie/api/random_films_api.py'>

  File "/Users/artem/Documents/PROGRAMMING/My/telebot/telebot_movie/api/random_films_api.py", line 29, in random_films_api
    content = data[0]
              └ {'status': None, 'externalId': {'imdb': 'tt0117030', 'tmdb': 64959}, 'rating': {'kp': 0, 'imdb': 5.6, 'filmCritics': 0, 'russ...

KeyError: 0
