2024-06-20 21:46:10.294 | INFO     | handlers.default_handlers.main_menu:bot_main:17 - Current state: UserInputState:main
2024-06-20 21:46:22.440 | INFO     | handlers.custom_handlers.random_handler:bot_rand_content:22 - Current state: UserInputState:rand
2024-06-20 21:46:56.056 | INFO     | handlers.default_handlers.main_menu:bot_main:17 - Current state: UserInputState:main
2024-06-20 21:47:05.461 | INFO     | handlers.custom_handlers.favorite_handler:show_favorite_movies:27 - Current state: UserInputState:favorite
2024-06-20 21:47:49.059 | INFO     | handlers.default_handlers.favorite:add_favorite:41 - Current state: UserInputState:waiting_favorite
2024-06-20 21:48:31.156 | INFO     | database.db_manager:add_favorite_movie:92 - Фильм "кака" добавлен в избранное пользователя с ID 961741922.
2024-06-20 21:48:31.402 | INFO     | handlers.default_handlers.favorite:handle_favorite_name:66 - Add favorite кака
2024-06-20 21:48:55.876 | INFO     | handlers.custom_handlers.favorite_handler:show_favorite_movies:27 - Current state: UserInputState:favorite
2024-06-20 21:49:05.745 | INFO     | handlers.default_handlers.history:user_history:29 - Current state: UserInputState:history
2024-06-20 21:49:05.942 | ERROR    | telebot:_run_middlewares_and_handler:6720 - An error has been caught in function '_run_middlewares_and_handler', process 'MainProcess' (90490), thread 'WorkerThread2' (6195785728):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x100bcbc40>
    └ <WorkerThread(WorkerThread2, started daemon 6195785728)>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x102536480>
    └ <WorkerThread(WorkerThread2, started daemon 6195785728)>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telebot/util.py", line 90, in run
    task(*args, **kwargs)
    │     │       └ {'handlers': [{'function': <function bot_start at 0x102776660>, 'pass_bot': False, 'filters': {'content_types': ['text'], 'co...
    │     └ (<telebot.types.Message object at 0x10279a050>,)
    └ <bound method TeleBot._run_middlewares_and_handler of <telebot.TeleBot object at 0x1024ac190>>
> File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telebot/__init__.py", line 6720, in _run_middlewares_and_handler
    result = handler['function'](message)
             │                   └ <telebot.types.Message object at 0x10279a050>
             └ {'function': <function user_history at 0x102777e20>, 'pass_bot': False, 'filters': {'content_types': ['text'], 'commands': ['...

  File "/Users/artem/Documents/PROGRAMMING/My/telebot/telebot_movie/handlers/default_handlers/history.py", line 34, in user_history
    bot.send_message(message.chat.id, history)
    │   │            │       │    │   └ None
    │   │            │       │    └ 961741922
    │   │            │       └ <telebot.types.Chat object at 0x1027a8f50>
    │   │            └ <telebot.types.Message object at 0x10279a050>
    │   └ <function TeleBot.send_message at 0x1025fde40>
    └ <telebot.TeleBot object at 0x1024ac190>

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telebot/__init__.py", line 1549, in send_message
    apihelper.send_message(
    │         └ <function send_message at 0x1025e0900>
    └ <module 'telebot.apihelper' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telebot/api...
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telebot/apihelper.py", line 264, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           │             │      │                  └ {'chat_id': '961741922', 'text': None}
           │             │      └ 'sendMessage'
           │             └ '6891552753:AAFMurqBrj6ROAvut_IJQoxapZ7HQVZnaQE'
           └ <function _make_request at 0x1025e00e0>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  │             │            └ <Response [400]>
                  │             └ 'sendMessage'
                  └ <function _check_result at 0x1025e02c0>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
          │                    │            │       └ {'ok': False, 'error_code': 400, 'description': 'Bad Request: message text is empty'}
          │                    │            └ <Response [400]>
          │                    └ 'sendMessage'
          └ <class 'telebot.apihelper.ApiTelegramException'>

telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty
